use Pharmacy;

SELECT DRUGS_INFO.NUMBER
	 , DRUGS_INFO.PRICE
	 , DRUGS_INFO.EXPIRY_DATE
	 , DRUGS.NAME
	 , DEALERS.NAME
	 , DEALERS.DISTRIBUTOR
	 , DEALERS.PHONE_NUMBER
FROM DRUGS_INFO
INNER JOIN DRUGS
	ON DRUGS_INFO.DRUG_ID = DRUGS.ID
INNER JOIN DEALERS
	ON DRUGS_INFO.DEALER_ID = DEALERS.ID;